### ISSUE TITLE
Word in Word - containing word is not highlighted

### ISSUE THREAD

**Issue by redskate** [mistic100/jquery-highlighttextarea#60]
Hi

in my case I would like to highlight 
"Name" and
"Simple_Name"
inside a text in  a text area.

It highlights only "Name"  ... This seems to me a bug. (why is there such behaviour?)

Thanks a lot
Cheers

**Comment by redskate** [comment]
ok, it seems I will have to fix it by myself ...

**Comment by mistic100** [comment]
Ho really sorry to be in holidays !

Beside your attitude I'll give you an answer : there is such "behavior" because once the first replacement is done, the html string does not match the next string anymore (because of highlight markup)

The only solution I see is just to define Simple_Name before Name in the words array.

**Comment by mistic100** [comment]
And before being condescending, read the note about development strauss in the read me, thank you.

**Comment by redskate** [comment]
I hope you enjoyed your holiday! And thank you for giving me an answer
despite of my attitude (by the way I also read other posts of yours here
observing your attitude: you are not much better ;)

Thank you for your "only solution": It does not work that way neither
(too simple). I used both orders (komplex first, komplex after) both the
same strange behaviour.

Well ... I hope you enjoy your time

You can close the issue - I will try to fix it by myself.

Fabio


Am 18.7.15 um 22:19 schrieb Damien Sorel:

**Comment by codeplay13** [comment]
I think this bug is still there.

@redskate Did you find any solution?
